version: '3'

tasks:
  start:
    desc: Start the application stack with Docker Compose
    cmds:
      - docker-compose up --build

  stop:
    desc: Stop the Docker Compose stack
    cmds:
      - docker-compose down -v

  test:
    desc: Run unit tests
    dir: backend
    cmds:
      - npm run test:unit

  test:integration:
    desc: Run integration tests against running application
    cmds:
      - chmod +x backend/scripts/integration-tests.sh
      - backend/scripts/integration-tests.sh
