version: '3'

tasks:
  start:
    desc: Start the application with Docker Compose in background
    cmds:
      - docker-compose up --build -d

  stop:
    desc: Stop the Docker Compose stack
    cmds:
      - docker-compose down -v

  test:
    desc: Run unit tests
    dir: api
    cmds:
      - npm run test:unit

  test:coverage:
    desc: Run tests with coverage report
    dir: api
    cmds:
      - npm run test:coverage

  test:integration:
    desc: Run integration tests against running application
    cmds:
      - chmod +x api/scripts/integration-tests.sh
      - api/scripts/integration-tests.sh
